# name: Build and Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: node.js configuracion
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: Build
#         run: npm run build -- --prod

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest

  #   steps:s
  #     - name: Deploy to S3
  #       uses: jakejarvis/s3-sync-action@master
  #       with:
  #         args: --acl public-read --follow-symlinks --delete
  #       env:
  #         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       if: success()

#   name: Build and Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: List dist files
#         run: ls && cd dist && ls 
      
#       - name: Configure AWS CLI
#         run: |
#           mkdir -p ~/.aws
#           echo "[default]" > ~/.aws/config
#           echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/config
#           echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/config
#           echo "region = us-east-2" >> ~/.aws/config
      
#       - name: aws s3 delete bucket archives
#         run: aws s3 rm s3://bucket-name --recursive
      
#       - name: aws s3 upload archives
#         run: aws s3 cp ./dist/nombre-de-proyecto s3://bucket-name --recursive

name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Installing Node js 
        uses: actions/checkout@v2

      - name: JUAN TEST 
        uses: actions/setup-node@v2
        with:
          node-version: '20'